Feature/linechart
FlockOfBirds/charts pull request #1
Opened 2017-08-09 07:36 UTC by akileng56

- Basic configurations
- Different data sources
- Web modeler preview

2017-08-09 11:54 UTC, edwinmp requested changes
Applies to bar chart too. For shared files, make changes in only one branch to avoid merge conflicts.

2017-08-09 11:54 UTC, edwinmp commented on .editorconfig
> +[{.babelrc,.stylelintrc,jest.config,.eslintrc,*.json,*.jsb3,*.jsb2,*.bowerrc}]
Remove any that aren't being used in your project. In this case, stay with only `[*.json]`

2017-08-09 11:54 UTC, edwinmp commented on .editorconfig
> +[*.coffee]
We got no coffee hehe

2017-08-09 11:54 UTC, edwinmp commented on .editorconfig
> +[tslint.json]
Will be handled in the `[*.json]`

2017-08-09 11:54 UTC, edwinmp commented on .editorconfig
> +[package.json]
Same here.

2017-08-09 11:54 UTC, edwinmp commented on Gruntfile.js
> +                files: [ "./dist/tmp/src/**/*" ],
Replace with `"./src/**/*"`

2017-08-09 11:54 UTC, edwinmp commented on Gruntfile.js
> +            sourceFiles: {
Remove this.

2017-08-09 11:54 UTC, edwinmp commented on Gruntfile.js
> +                files: [ {
Can be done better.
```
// somewhere at the top
const widgetNames = [ 'BarChart', 'LineChart' ];
...
files: widgetNames.map(widgetName => { append: `\n\n//# sourceURL=${widget}.webmodeler.js\n`, ... }
```

2017-08-09 11:54 UTC, edwinmp commented on Gruntfile.js
> +            source: {
Remove.

2017-08-09 11:54 UTC, edwinmp commented on karma.conf.js
> +            { pattern: "src/**/*.ts", watched: true, included: false, served: false },
Remove `included` & `served`

2017-08-09 11:54 UTC, edwinmp commented on karma.conf.js
> +            { pattern: "tests/**/*.ts", watched: true, included: false, served: false },
Remove `included` & `served`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.d.ts
> +/* tslint:disable */
Nope... noooo. Disable for a line, not an entire file.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +        <property key="seriesEntity" type="entity" isPath="yes" pathType="referenceSet">
Shouldn't be a path... Don't tie to context. Let connection be made via XPath.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Series entity</description>
Improve description, or remove if identical to caption.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Series name attribute</description>
Describe ... for reals this time. `Attribute that holds the name of the series`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Data entity</description>
Add decent description or remove if identical to caption. `<description/>`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <caption>Source</caption>
`Data source` or `Data source type`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +        <property key="sourceType" type="enumeration" defaultValue="xpath">
`dataSourceType`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <caption>Source</caption>
**Data** bit is important. Could be the source of the Nile for all we know.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Type of source</description>
Can ditch the description.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +                <enumerationValue key="xpath">Database</enumerationValue>
`XPath`
Both key & caption. Maybe caption can be Database/XPath

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <caption>Source XPath Constraint</caption>
`XPath constraint`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Constraint on the data from the data entity</description>
Explain that it's only application when `data source type` is `XPath`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <caption>Source microflow</caption>
`Microflow`
We already know this is related to the data source since it's in the `Data source` tab

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Returns a lines' coordinates</description>
Really? Is this what it really does? Copy/Paste fail. :)

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>X value attribute</description>
Remove. `<description/>`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Y value attribute</description>
Same here.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +                <enumerationValues>
These values don't match the ones u specified in your .d.ts. Sync please.
https://github.com/FlockOfBirds/charts/pull/1/files#diff-fd0e5652e46f9cf18941a9c9920f6ae6R4

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <description>Line color</description>
Doesn't match caption. Remove.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/LineChart.xml
> +            <caption>Show grids</caption>
`Show grid`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/Alert.ts
> +export const Alert: StatelessComponent<{ message?: string }> = (props) =>
Make generic. Refer to RichText. Also, move this outside the LineChart folder to a shared component folder. Do it in the shared branch and rebase ... :)

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +
Remove blank line.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +declare function require(name: string): string;
Set `lib: [ "es2015", "dom" ]` in tsconfig.json, then remove this line.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +
Remove blank line.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +                ...this.getStyle()
Flip these two. Styles from the modeler should overwrite your own.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +                wrapperElement.style.height = "100%";
How's this percentage of parent??? Not seeing any calculations of the percentage height of the parent or where its being set to the widget.
Perhaps I'm not getting it...
`PercentageOfParent = (percentageSpecified * parentHeight)%`

If mistaken, add comment to explain the purpose of this code. Not clear.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +            iFrame.contentWindow.addEventListener("resize", this.onResize);
Check for either `contentWindow` or `contentDocument`. Crossbrowser compatible
```
const x = document.getElementById("myframe");
const y = (x.contentWindow || x.contentDocument);
```

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +    private getIframe(): HTMLIFrameElement {
You're using this only once, and it has one line... inline.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +        const style: { paddingBottom?: string; width: string, height?: string } = {
Set type to CSSProperties.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChart.ts
> +            style.height = `${this.props.height}%`;
FYI, this is where percentage of parent is set. Know your code :)

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +import { LineChart } from "./LineChart";
Alphabetize imports.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +        } else {
Remove else.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +            return createElement("div", {});
`Return null;`
Unless there's some significance to returning a blank div.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +        this.fetchData(this.props.mxObject);
How is this handling subscription?

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +        this.fetchData(this.props.mxObject);
Actually, this function (handleSubscription) isn't being used at all.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +                const constraint = this.props.entityConstraint
Do this stuff inside the `this.fetchByXPath()` function

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +                const constraint = this.props.entityConstraint
Expect only a call to `this.fetchByXPath()` here.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +                alertMessage: `An error occurred while retrieving data via XPath (${xpath}): ${error}`,
This is not a configuration error, so use `mx.ui.error()` to display it.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +            error: error => this.setState({
This is not a configuration error, so use `mx.ui.error()` to display it.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +            callback: mxObjects => {
`callback: mxObjects => this.fetchDataFromSeries(mxObjects as mendix.lib.MxObject[]),`

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +                    error: error => this.setState({
Don't use alert.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +            const data: DataProps = {
No need for an object here. Just create individual variables for whatever u need. Unless you're passing in the entire data variable somewhere.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/components/LineChartContainer.ts
> +export { LineChartContainer as default, LineChartContainerProps };
Inline export.

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/ui/LineChart.css
> +    width: 100% !important;
Why important?

2017-08-09 11:54 UTC, edwinmp commented on src/LineChart/ui/LineChart.css
> +    width: 100% !important;
Why important?

2017-08-10 08:04 UTC, akileng56 commented on Gruntfile.js
> +            source: {
Breaks the mpk build when removed

2017-08-10 08:05 UTC, akileng56 commented on Gruntfile.js
> +            sourceFiles: {
Removed

2017-08-10 08:05 UTC, akileng56 commented on Gruntfile.js
> +                files: [ "./dist/tmp/src/**/*" ],
Replaced

2017-08-10 08:05 UTC, akileng56 commented on .editorconfig
> +[*.coffee]
Removed

2017-08-10 08:05 UTC, akileng56 commented on .editorconfig
> +[tslint.json]
Removed

2017-08-10 08:05 UTC, akileng56 commented on .editorconfig
> +[package.json]
Removed

2017-08-10 08:05 UTC, akileng56 commented on .editorconfig
> +[{.babelrc,.stylelintrc,jest.config,.eslintrc,*.json,*.jsb3,*.jsb2,*.bowerrc}]
Removed

2017-08-10 14:17 UTC, akileng56 commented on karma.conf.js
> +            { pattern: "src/**/*.ts", watched: true, included: false, served: false },
Removed

2017-08-10 14:17 UTC, akileng56 commented on karma.conf.js
> +            { pattern: "tests/**/*.ts", watched: true, included: false, served: false },
Removed

2017-08-11 06:13 UTC, akileng56 commented on src/LineChart/LineChart.d.ts
> +/* tslint:disable */
Changed

2017-08-11 06:13 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +        <property key="seriesEntity" type="entity" isPath="yes" pathType="referenceSet">
Fixed

2017-08-11 06:13 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Series entity</description>
Done

2017-08-11 06:13 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Series name attribute</description>
Fixed

2017-08-11 06:13 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Data entity</description>
Done

2017-08-11 06:13 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +        <property key="sourceType" type="enumeration" defaultValue="xpath">
Changed

2017-08-11 06:14 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <caption>Source</caption>
Hehe...Changed

2017-08-11 06:47 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Type of source</description>
Done

2017-08-11 06:48 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +                <enumerationValue key="xpath">Database</enumerationValue>
Done

2017-08-11 06:48 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <caption>Source XPath Constraint</caption>
Fixed

2017-08-11 06:48 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Constraint on the data from the data entity</description>
Done

2017-08-11 06:48 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <caption>Source microflow</caption>
Changed

2017-08-11 06:49 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Returns a lines' coordinates</description>
Fixed

2017-08-11 06:49 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>X value attribute</description>
Removed

2017-08-11 06:49 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Y value attribute</description>
Changed

2017-08-11 06:49 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +                <enumerationValues>
Done

2017-08-11 06:50 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <description>Line color</description>
Removed

2017-08-11 06:50 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +            <caption>Show grids</caption>
Done

2017-08-11 06:50 UTC, akileng56 commented on src/LineChart/components/Alert.ts
> +export const Alert: StatelessComponent<{ message?: string }> = (props) =>
Fixed

2017-08-11 06:51 UTC, akileng56 commented on src/LineChart/components/LineChart.ts
> +
Removed

2017-08-14 05:58 UTC, akileng56 commented on src/LineChart/components/LineChart.ts
> +
Removed

2017-08-14 05:58 UTC, akileng56 commented on src/LineChart/components/LineChart.ts
> +                ...this.getStyle()
Changed

2017-08-14 06:00 UTC, akileng56 commented on src/LineChart/components/LineChart.ts
> +                wrapperElement.style.height = "100%";
This makes sure the parent is always at 100% so that the child height can be set to percentage of the height

2017-08-14 06:00 UTC, akileng56 commented on src/LineChart/components/LineChart.ts
> +            iFrame.contentWindow.addEventListener("resize", this.onResize);
Added

2017-08-14 06:00 UTC, akileng56 commented on src/LineChart/components/LineChart.ts
> +    private getIframe(): HTMLIFrameElement {
Fixed

2017-08-14 06:02 UTC, akileng56 commented on src/LineChart/components/LineChart.ts
> +        const style: { paddingBottom?: string; width: string, height?: string } = {
Won't this require creating separate typings for it...object can work for now

2017-08-14 06:02 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +import { LineChart } from "./LineChart";
Done

2017-08-14 06:02 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +        } else {
Removed

2017-08-14 06:03 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +            return createElement("div", {});
Nothing special in returning a blank div. null is fine

2017-08-14 06:03 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +        this.fetchData(this.props.mxObject);
Removed

2017-08-14 06:03 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +                const constraint = this.props.entityConstraint
Done

2017-08-14 06:03 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +                alertMessage: `An error occurred while retrieving data via XPath (${xpath}): ${error}`,
Fixed

2017-08-14 06:03 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +            callback: mxObjects => {
Done

2017-08-14 06:04 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +            error: error => this.setState({
Done

2017-08-14 06:04 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +            const data: DataProps = {
Fixed

2017-08-14 06:04 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +                    error: error => this.setState({
Fixed

2017-08-14 06:04 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +export { LineChartContainer as default, LineChartContainerProps };
Done

2017-08-14 06:05 UTC, akileng56 commented on src/LineChart/ui/LineChart.css
> +    width: 100% !important;
Overriding inline styling from the plotly lib. This is actually not needed

2017-08-14 06:05 UTC, akileng56 commented on src/LineChart/ui/LineChart.css
> +    width: 100% !important;
Overriding inline styling from the plotly lib. This is actually not needed

2017-08-15 14:19 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +        <property key="seriesEntity" type="entity" isPath="yes" pathType="referenceSet">
Done

2017-08-15 14:20 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <description>Series entity</description>
Done

2017-08-15 14:20 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <description>Series name attribute</description>
Done

2017-08-15 14:20 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <description>Data entity</description>
Done

2017-08-15 14:20 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +        <property key="sourceType" type="enumeration" defaultValue="xpath">
Done

2017-08-15 14:20 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <caption>Source</caption>
Done

2017-08-15 14:20 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <description>Type of source</description>
Done

2017-08-15 14:21 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +                <enumerationValue key="xpath">Database</enumerationValue>
Done

2017-08-15 14:21 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <caption>Source XPath Constraint</caption>
Done

2017-08-15 14:21 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <description>Constraint on the data from the data entity</description>
Done

2017-08-15 14:21 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <caption>Source microflow</caption>
Done

2017-08-15 14:21 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <description>Returns a lines' coordinates</description>
Done

2017-08-15 14:22 UTC, McDoyen commented on src/LineChart/LineChart.xml
> +            <description>X value attribute</description>
Done

2017-08-15 14:24 UTC, McDoyen commented on src/LineChart/components/LineChart.ts
> +            iFrame.contentWindow.addEventListener("resize", this.onResize);
Done

2017-09-15 07:43 UTC, closed without merging