Feature/piechart
FlockOfBirds/charts pull request #3
Opened 2017-08-11 00:33 UTC by mistaguy

2017-08-11 02:06 UTC, acellam commented on Gruntfile.js
> +});
this is better

2017-08-11 02:06 UTC, acellam commented on Gruntfile.js
> +});
```
const webpackConfigRelease = webpackConfig.map(config => merge(config, {
    devtool: false,
    plugins: [ new webpack.optimize.UglifyJsPlugin() ]
}));```

2017-08-11 02:06 UTC, acellam commented on Gruntfile.js
> +                    livereload: true
Remove coz it is not available since wepack 2 `livereload`. We are supposed to be using `Hot Module Replacement`  and `webpack-dev-server` supports it.

2017-08-11 02:06 UTC, acellam commented on package.json
> +    "@types/draft-js": "^0.10.1",
Do u really need `draft-js` ?

2017-08-11 02:06 UTC, acellam commented on package.json
> +    "fs": "0.0.1-security",
do u need this `fs`

2017-08-11 02:06 UTC, acellam commented on package.json
> +    "mendix-client": "https://github.com/FlockOfBirds/Mendix-client-typing/archive/7.1.0.tar.gz",
use 7.3.0

2017-08-11 02:06 UTC, acellam commented on package.json
> +    "webpack": "^2.3.1",
can we go webpack 3 already?

2017-08-11 02:06 UTC, acellam commented on tsconfig.json
> +    "skipLibCheck": true,
false

2017-08-11 02:06 UTC, acellam commented on tsconfig.json
> +    "strictNullChecks": true,
remove all these
```
     "noImplicitAny": true,
     "noImplicitReturns": true,
     "noImplicitThis": true,
     "strictNullChecks": true,
```
and replace with this

```
"alwaysStrict": true

```

2017-08-11 02:06 UTC, acellam commented on src/package.xml
> +            <widgetFile path="Charts/LineChart/LineChart.xml"/>
where is the `pie chart`

2017-08-11 02:06 UTC, acellam commented on webpack.config.js
> +    },
where is `pie chart`

2017-08-11 02:06 UTC, acellam commented on webpack.config.js
> +        extensions: [ ".ts", ".js", ".json" ],
i think you can live without `json`

2017-08-11 02:06 UTC, acellam commented on webpack.config.js
> +        BarChart: "./src/Charts/BarChart/BarChart.webmodeler.ts",
u can also use `${widgetName}`

2017-08-11 02:06 UTC, acellam commented on .editorconfig
> +[{.babelrc,.stylelintrc,jest.config,.eslintrc,*.json,*.jsb3,*.jsb2,*.bowerrc}]
not very readable, add spacing

2017-08-11 02:06 UTC, acellam commented on .editorconfig
> +charset=utf-8
is it possible to have space on assignment?
If so can it be done for all the relevant assignments in this file?

2017-08-11 02:06 UTC, acellam commented on .editorconfig
> +[{.babelrc,.stylelintrc,jest.config,.eslintrc,*.json,*.jsb3,*.jsb2,*.bowerrc}]
only add options relevant to our project

2017-08-11 02:06 UTC, acellam commented on .editorconfig
> +[*.coffee]
not relevant, remove

2017-08-11 02:06 UTC, acellam commented on src/LineChart/components/LineChartContainer.ts
> +export { LineChartContainer as default };
inline default

2017-08-11 02:06 UTC, acellam commented on src/BarChart/BarChart.webmodeler.ts
> +import { Component, DOM } from "react";
don not use DOM any more

2017-08-11 02:06 UTC, acellam commented on src/BarChart/BarChart.webmodeler.ts
> +        return DOM.div();
don not use DOM any more

2017-08-11 02:06 UTC, acellam commented on src/BarChart/components/BarChartContainer.ts
> +export { BarChartContainer as default };
inline default

2017-08-11 02:06 UTC, acellam commented on src/LineChart/LineChart.webmodeler.ts
> +        return DOM.div();
don not use DOM any more

2017-08-11 02:06 UTC, acellam commented on src/LineChart/LineChart.webmodeler.ts
> +import { Component, DOM } from "react";
don not use DOM any more

2017-08-11 02:06 UTC, acellam commented on src/PieChart/PieChart.xml
> +            <description></description>
Provide description

2017-08-11 02:06 UTC, acellam commented on src/PieChart/PieChart.xml
> +    <description>Create Pie chart</description>
better description or no description at all

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChart.ts
> +    data?: any[];
dont use any

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChart.ts
> +    private Plotly: PlotlyStatic;
it is a variable so why not `plotly`

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChart.ts
> +    private data: any[] = [ {
dont use any

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChart.ts
> +        this.Plotly = require("plotly.js/dist/plotly") as any;
dont use any

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChart.ts
> +        const { data, config, layout } = props;
separate variable declaration from the next code block

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChart.ts
> +
remove space

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChart.ts
> +export { PieChart };
inline export

2017-08-11 02:06 UTC, acellam commented on src/PieChart/components/PieChartContainer.ts
> +export type ChartType = "pie" | "donut";
to keep the flow of code i would prefer ChartType to come before the props

2017-08-11 02:06 UTC, mistaguy commented on src/BarChart/BarChart.xml
> +    <description>Create Bar chart</description>
`Create bar chart`

2017-08-11 02:06 UTC, mistaguy commented on src/LineChart/LineChart.xml
> +    <description>Create Line chart</description>
`Create line chart`

2017-08-11 02:30 UTC, mistaguy commented on karma.conf.js
> +            { pattern: "src/**/*.ts", watched: true, included: false, served: false },
Remove `included` and `served`

2017-08-11 02:30 UTC, mistaguy commented on karma.conf.js
> +            { pattern: "tests/**/*.ts", watched: true, included: false, served: false },
Remove `included` and `served`

2017-08-11 02:30 UTC, mistaguy commented on src/BarChart/BarChart.xml
> +            <description>Chart title</description>
better description or no description at all

2017-08-14 05:30 UTC, akileng56 commented on package.json
> +    "@types/draft-js": "^0.10.1",
Removed

2017-08-14 05:30 UTC, akileng56 commented on Gruntfile.js
> +                    livereload: true
Fixed in the Basic branch need to rebase

2017-08-14 05:31 UTC, akileng56 commented on package.json
> +    "fs": "0.0.1-security",
Removed

2017-08-14 05:31 UTC, akileng56 commented on package.json
> +    "mendix-client": "https://github.com/FlockOfBirds/Mendix-client-typing/archive/7.1.0.tar.gz",
Updated

2017-08-14 05:31 UTC, akileng56 commented on package.json
> +    "webpack": "^2.3.1",
Updated

2017-08-14 05:31 UTC, akileng56 commented on tsconfig.json
> +    "skipLibCheck": true,
Added

2017-08-14 05:31 UTC, akileng56 commented on tsconfig.json
> +    "strictNullChecks": true,
Removed

2017-08-14 05:32 UTC, akileng56 commented on .editorconfig
> +charset=utf-8
Yes, it's possible to have space. Added

2017-08-14 05:33 UTC, akileng56 commented on .editorconfig
> +[{.babelrc,.stylelintrc,jest.config,.eslintrc,*.json,*.jsb3,*.jsb2,*.bowerrc}]
Removed....Rebase from basic branch

2017-08-14 05:33 UTC, akileng56 commented on .editorconfig
> +[*.coffee]
Removed....Rebase from basic branch

2017-08-14 05:33 UTC, akileng56 commented on src/LineChart/components/LineChartContainer.ts
> +export { LineChartContainer as default };
Handled in the Line chart branch

2017-08-14 05:34 UTC, akileng56 commented on src/BarChart/BarChart.webmodeler.ts
> +import { Component, DOM } from "react";
Handled in the bar chart branch

2017-08-14 05:34 UTC, akileng56 commented on src/BarChart/BarChart.webmodeler.ts
> +        return DOM.div();
Handled in the bar chart branch

2017-08-14 05:34 UTC, akileng56 commented on src/BarChart/components/BarChartContainer.ts
> +export { BarChartContainer as default };
Handled in the barchart branch

2017-08-14 05:34 UTC, akileng56 commented on src/LineChart/LineChart.webmodeler.ts
> +import { Component, DOM } from "react";
Handled in the Line chart branch

2017-08-14 05:34 UTC, akileng56 commented on src/LineChart/LineChart.webmodeler.ts
> +        return DOM.div();
Handled in the Line chart branch

2017-08-14 05:38 UTC, akileng56 commented on src/PieChart/PieChart.xml
> +    <description>Create Pie chart</description>
Updated

2017-08-14 05:40 UTC, akileng56 commented on src/PieChart/PieChart.xml
> +            <description></description>
Added

2017-08-14 05:44 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +
Removed

2017-08-14 05:44 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +        const { data, config, layout } = props;
Fixed

2017-08-14 05:45 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +        this.Plotly = require("plotly.js/dist/plotly") as any;
Need to update or create  typings

2017-08-14 05:45 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +    private data: any[] = [ {
Need to update or create  typings

2017-08-14 05:45 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +    private Plotly: PlotlyStatic;
True, updated

2017-08-14 05:45 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +    data?: any[];
Need to update or create  typings

2017-08-14 05:46 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +export { PieChart };
Fixed

2017-08-14 05:46 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +export type ChartType = "pie" | "donut";
Fixed

2017-08-14 05:46 UTC, akileng56 commented on src/BarChart/BarChart.xml
> +    <description>Create Bar chart</description>
Handled in the bar chart branch

2017-08-14 05:46 UTC, akileng56 commented on src/LineChart/LineChart.xml
> +    <description>Create Line chart</description>
Handled in the linechart branch

2017-08-14 05:47 UTC, akileng56 commented on karma.conf.js
> +            { pattern: "src/**/*.ts", watched: true, included: false, served: false },
Removed...Rebase from basic branch

2017-08-14 05:47 UTC, akileng56 commented on karma.conf.js
> +            { pattern: "tests/**/*.ts", watched: true, included: false, served: false },
Removed...Rebase from basic branch

2017-08-14 05:48 UTC, akileng56 commented on src/BarChart/BarChart.xml
> +            <description>Chart title</description>
Handled in bar chart branch

2017-08-16 15:38 UTC, edwinmp requested changes
Strictly GitHub based review. Haven't looked at it in an IDE yet.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +import { Alert } from "../components/Alert";
Alphabetise grouped imports.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +declare function require(name: string): string;
This should already exist in shared file in the typings folder. If not, add it there & remove it here.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +            }),
Your Alert component needs no bootstrap class, or has one by default?

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +                    displayModeBar: this.props.showToolBar
It's just one tiny property. Move to line 22.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +                    hole: this.props.chartType === "donut" ? .4 : 0,
Shouldn't the size of the doughnut hole be configurable? I think so... In fact, I think this is what should be used to determine whether the chart is a doughnut or not, instead of the chartType. Defaults to 0.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +                data: [ {
hmm... Perhaps u could move this entire object into a function called `defaultData` or something.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +                type: this.props.chartType,
As far as I can tell from the documentation, there is no `"donut"` `chartType`, and yet u have it as a possible value. Donut is decided by the `hole` property, so this `chartType `config should go cos it'll always be `pie`.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +    return require("plotly.js/src/css/style.scss");
Don't u have your own custom` CSS` to add here?

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.webmodeler.ts
> +    if (valueMap.dataSourceType === "xpath") {
I remember asking this `xpath` to be changed to `XPath`. This was based on feedback from Johan on the carousel.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.xml
> +        <property key="dataSourceType" type="enumeration" defaultValue="xpath">
`XPath`

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.xml
> +                <enumerationValue key="xpath">Database / XPath</enumerationValue>
`XPath`

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.xml
> +            <description>Attribute containing the name to describing the value</description>
`Attribute containing the name describing a value`

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.xml
> +        <property key="sortAttribute" type="attribute" entityProperty="dataEntity">
Do these really need to be sorted? I don't think so. They're in a circle. A circle is infinite, no beginning, no end, so position doesn't matter.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/PieChart.xml
> +        </property>
Correct indentation.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +    private plotly: PlotlyStatic;
Remove this. Use `Plotly`, as imported up there.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +        labels: [ "US", "China", "European Union", "Russian Federation", "Brazil", "India", "Rest of World" ],
Consult client on what should appear in default data.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +        this.plotly = Plotly;
Remove.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +            className: classNames(`widget-${this.props.type}-chart`, this.props.className),
👍

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +                ...this.props.style
Inline both properties. They're neat enough to look good on one line.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +    private pieChart: HTMLDivElement;
Misleading name. Perhaps `pieChartNode`.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +            this.plotly.newPlot(this.pieChart, data && data.length ? data : this.data, layout, config);
According to AS, not very ready to have a ternary operator in certain places, such as this. Extract it. As a result, ditch the destructuring on line 75.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +            const wrapperElement = this.pieChart.parentElement;
Wrapper will not exist no more, so just name `parentElement`

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +            const wrapperElement = this.pieChart.parentElement;
In fact, since there's no wrapper, this entire function is obsolete, so remove it. Confirm with Guy.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +        const style: { paddingBottom?: string; width: string, height?: string } = {
Remember giving feedback on a better type for this in the LineChart...

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +        return style;
Blank line before.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChart.ts
> +        this.plotly.Plots.resize(this.pieChart);
`Plotly.Plots.resize`

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +        return null;
What is the point of the default data you define in the PieChart component when u return null when there's no context object? Under what circumstances is the default data used?

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +                        colors: this.state.colors
Inline.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +    public static parseStyle(style = ""): { [key: string]: string } {
Move the `public static` stuff to the end of the class.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +    public static validateProps(props: PieChartContainerProps): string {
Same here.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +        this.subscriptionHandles.forEach(mx.data.unsubscribe);
Sooooo, Mr. Akileng, whhhy do we have an array for this subscriptionHandles when it only ever has one item? Why?? :)

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +                callback: () => this.fetchData(mxObject),
Can do without the mxObject property and have it as `callback: this.fetchData`. In `fetchData`, use `this.props.mxObject`. It'll be fine. By the time subscriptions are triggered, component shall always have the updated version of mxObject.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +        this.colors = []; this.labels = []; this.values = [];
Separate lines.

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +            callback: mxObjects => this.processData(mxObjects),
Can be shorted to `callback: this.processData`

2017-08-16 15:38 UTC, edwinmp commented on src/PieChart/components/PieChartContainer.ts
> +        });
As far as I can tell, these properties (`colors, labels, values`) are only useful in this function. You can have the same functionality with them created locally in this file. Come we do it when u get to this point.... biwanvu at the moment.

2017-08-16 15:38 UTC, edwinmp commented on src/components/Alert.ts
> +        ? createElement("div", { className: classNames("alert alert-danger", className) }, message)
Make generic... includes making sure your alert can support more than just the `danger` variety. Refer to other widgets, or Paul.

2017-08-16 15:38 UTC, edwinmp commented on tsconfig.json
> +    "alwaysStrict": true,
Rebase `feature/basic` to pull the right property for this. Should be `strict`, not `alwaysStrict`.

2017-08-17 07:00 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +import { Alert } from "../components/Alert";
Done

2017-08-17 08:16 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +declare function require(name: string): string;
Updated

2017-08-17 08:18 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +            }),
Added the bootstrap class

2017-08-17 08:18 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +                    displayModeBar: this.props.showToolBar
Done

2017-08-17 08:34 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +                data: [ {
Function seems smarter....Added it

2017-08-17 09:06 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +                    hole: this.props.chartType === "donut" ? .4 : 0,
it's only the type that was specified on the feature sheet...maybe we can  ask the client 
https://docs.google.com/spreadsheets/d/1jfguDHL36jxeyZjxS8WWlc7DcCdwJO3Y5BWkuvSjbIM/edit#gid=0

2017-08-17 09:11 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +                type: this.props.chartType,
Yes, but the hole property is not in the excel sheet... Maybe we can consult with the client.

2017-08-17 09:12 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +    return require("plotly.js/src/css/style.scss");
I don't have any at the moment

2017-08-17 09:13 UTC, akileng56 commented on src/PieChart/PieChart.webmodeler.ts
> +    if (valueMap.dataSourceType === "xpath") {
Fixed

2017-08-17 09:13 UTC, akileng56 commented on src/PieChart/PieChart.xml
> +        <property key="dataSourceType" type="enumeration" defaultValue="xpath">
Fixed

2017-08-17 09:14 UTC, akileng56 commented on src/PieChart/PieChart.xml
> +            <description>Attribute containing the name to describing the value</description>
Done

2017-08-17 09:15 UTC, akileng56 commented on src/PieChart/PieChart.xml
> +        <property key="sortAttribute" type="attribute" entityProperty="dataEntity">
Yeah true..

2017-08-17 09:19 UTC, akileng56 commented on src/PieChart/PieChart.xml
> +        </property>
Fixed

2017-08-17 09:33 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +    private pieChart: HTMLDivElement;
Done

2017-08-17 10:25 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +        labels: [ "US", "China", "European Union", "Russian Federation", "Brazil", "India", "Rest of World" ],
Will do

2017-08-17 11:52 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +        this.plotly = Plotly;
Removed....

2017-08-17 11:55 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +                ...this.props.style
Done

2017-08-17 12:13 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +            this.plotly.newPlot(this.pieChart, data && data.length ? data : this.data, layout, config);
Done...though line 75 is still needed.

2017-08-17 12:31 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +            const wrapperElement = this.pieChart.parentElement;
Yes its not needed

2017-08-17 12:31 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +        const style: { paddingBottom?: string; width: string, height?: string } = {
Yes ..CSSProperties...Added them

2017-08-17 12:31 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +        return style;
Done

2017-08-17 12:32 UTC, akileng56 commented on src/PieChart/components/PieChart.ts
> +        this.plotly.Plots.resize(this.pieChart);
Done

2017-08-17 12:37 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +                        colors: this.state.colors
Done

2017-08-17 12:41 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +        return null;
It's shown when there is a context object and values retrieved from DB or by  micro flow are empty

2017-08-17 12:42 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +    public static parseStyle(style = ""): { [key: string]: string } {
Done

2017-08-17 12:43 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +    public static validateProps(props: PieChartContainerProps): string {
Done

2017-08-17 12:51 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +        this.subscriptionHandles.forEach(mx.data.unsubscribe);
Removed.... it's actually not need...

2017-08-17 13:07 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +                callback: () => this.fetchData(mxObject),
Done

2017-08-17 13:08 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +        this.colors = []; this.labels = []; this.values = [];
Done

2017-08-17 13:08 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +            callback: mxObjects => this.processData(mxObjects),
Done

2017-08-17 13:08 UTC, akileng56 commented on src/PieChart/components/PieChartContainer.ts
> +        });
Done

2017-08-17 13:09 UTC, akileng56 commented on src/components/Alert.ts
> +        ? createElement("div", { className: classNames("alert alert-danger", className) }, message)
Done

2017-09-15 07:43 UTC, closed without merging